export const PUT_CANDIDATE = 'PUT_CANDIDATE';
export const DELETE_CANDIDATE = 'DELETE_CANDIDATE';
export const SET_CANDIDATES = 'SET_CANDIDATES';
export const UPLOAD_DOCUMENT_SUCCESS = 'UPLOAD_DOCUMENT_SUCCESS';
export const UPLOAD_DOCUMENT_FAIL = 'UPLOAD_DOCUMENT_FAIL';
